server:
  port: 9000
database:
  type: "sqlite" # mysql / mariadb / postgres / sqlite
  host: "127.0.0.1"
  port: 5432
  dbname: "dbname"
  username: "username"
  password: "password" # TODO from env
